### ISSUE TITLE
clamav-mirror Will not deploy without modifications

### ISSUE THREAD

**Issue by antitux** [mxplusb/clamav#5]
2 modifications should be documented to build and deploy this properly:
1. `.cfignore` needs `*vendor/` commented out
2. `GOVERSION` needs to be set to at least `go1.11` (though it does seem to work with `go1.12` also)

Correct `cf push` steps would be the following:
1. remove `*vendor/` from `.cfignore`
2. set `GOVERSION` to `go1.11` or above.
3. `cf push`

**Comment by siennathesane** [comment]
Hi @antitux, sorry for the delays, I had this archived as I didn't have time to work on it. I unarchived it, but I removed the cloud foundry information since I don't want to maintain it right now. You're welcome to submit a PR if you still need that.
